#!/bin/sh


#----------Commit logger hook----------
NOW=$(date +"%m-%d-%Y")
LOGFILE="$HOME/git_commit_logs/commits.$NOW.log"

if [ ! -f "$LOGFILE" ]
then
    echo "file or dir does not exist"
    echo $LOGFILE
	touch $LOGFILE
fi

echo "-----------------------------------" >> $LOGFILE
pwd >> $LOGFILE
git log -1 --format="%cd %B" --date=iso >> $LOGFILE
echo "-----------------------------------" >> $LOGFILE
#----------Commit logger hook ends----------