#!/bin/sh

# Copy last commit hash to clipboard on commit
#git log -1 --format=format:%h | pbcopy

# Add other post-commit hooks

NOW=$(date +"%m-%d-%Y")
LOGFILE="~/git_commit_logs/commits.$NOW.log"

if [ ! -f "$LOGFILE" ]
then
	touch "$LOGFILE"
fi

echo "-----------------------------------" >> $LOGFILE
pwd >> $LOGFILE
git log -1 --format="%cd %B" --date=iso >> $LOGFILE
echo "-----------------------------------" >> $LOGFILE
